#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2020 Tuomas Siipola
# SPDX-License-Identifier: AGPL-3.0-or-later
set -e

URLS=(
    "https://s3-us-west-1.amazonaws.com/photos.snapwi.re/Week+88/Josh+Felise.jpg"
    "https://s3-us-west-1.amazonaws.com/photos.snapwi.re/Week+21/SW_DominikMartin.jpg"
    "https://s3-us-west-1.amazonaws.com/photos.snapwi.re/Week+189/SW_Michael+Day.jpg"
)

for i in {1..3}; do
    if [ ! -f images/image$i.jpg ]; then
        curl -s ${URLS[i-1]} -o images/image$i.jpeg
    fi
done

echo "| Original | Optimized JPEG | Optimized WebP |"
echo "| - | - | - |"

META=(
    "Photo: [Josh Felise](https://www.snapwi.re/user/JPFelise)<br>[CC0 1.0](https://creativecommons.org/publicdomain/zero/1.0/) &bullet; [Source](https://snapwiresnaps.tumblr.com/post/140752672614/josh-felise-free-under-cc0-10-download)"
    "Photo: [Dominik Martin](https://www.snapwi.re/user/dominikmartn)<br>[CC0 1.0](https://creativecommons.org/publicdomain/zero/1.0/) &bullet; [Source](https://snapwiresnaps.tumblr.com/post/102447448703/dominik-martin-wwwdominikmartin-free)"
    "Photo: [Michael Day](https://www.snapwi.re/user/bucktownchicago)<br>[CC0 1.0](https://creativecommons.org/publicdomain/zero/1.0/) &bullet; [Source](https://snapwiresnaps.tumblr.com/post/171101090646/michael-day-free-under-cc0-10-download)"
)

for i in {1..3}; do
    original="images/image$i.jpeg"
    thumbnail="images/image$i-original.png"
    magick convert "$original" -resize 200x "$thumbnail"

    jpeg="images/image$i-jpeg.jpeg"
    jpeg_quality=$(cargo run --release -- "$thumbnail" -o "$jpeg" 2>&1 | tail -n1 | cut -c 29-30)
    jpeg_size=$(stat -c %s "$jpeg")
    jpeg_size=$(numfmt --to=iec $jpeg_size)iB
    magick convert "$jpeg" "images/image$i-jpeg.png"
    rm "$jpeg"
    jpeg="images/image$i-jpeg.png"

    webp="images/image$i-webp.webp"
    webp_quality=$(cargo run --release -- "$thumbnail" -o "$webp" 2>&1 | tail -n1 | cut -c 29-30)
    webp_size=$(stat -c %s "$webp")
    webp_size=$(numfmt --to=iec $webp_size)iB
    magick convert "$webp" "images/image$i-webp.png"
    rm "$webp"
    webp="images/image$i-webp.png"

    echo "| ![]($thumbnail)<br>${META[i-1]} | ![]($jpeg)<br>**File size:** $jpeg_size<br>**Quality:** $jpeg_quality | ![]($webp)<br>**File size:** $webp_size<br>**Quality:** $webp_quality |"
done
